### PR TITLE
fix prefs and force restart (fixes #32 and #33)

### LINKED ISSUE #32: When extension is installed, prefs do not get respected
So when the extension is installed at all, it looks the prefs aren't getting changed. And even manually overriding the prefs from `about:config` doesn't work. Only until you uninstall the extension do manual pref changes get respected.
1. Install the [extension](https://addons.mozilla.org/en-US/developers/addon/mozilla-webvr-enabler/).
2. From `about:config` search for `.vr.`
3. Notice a bunch of VR-specific prefs are flipped.
4. Load http://mozvr.com/ or http://aframe.io/examples/ and notice the pref settings don't seem to be in effect.
5. Relaunch Firefox (once or a few times).
6. Notice the prefs still don't seem to be in effect.
7. Manually reset the prefs (e.g., toggle `gfx.vr.mirror-textures` and set it to `true`).
8. Notice the pref doesn't seem to work because nothing's mirrored.
9. Uninstall the extension.
10. From `about:config`, manually set the VR-specific prefs (e.g., toggle `gfx.vr.mirror-textures` and set it to `true`).
11. Voilà, things work. :sob:

### PR DESCRIPTION
**Pull request by cvan**
r? @caseyyee @kearwood 

[Use this `.xpi` to test](https://drive.google.com/file/d/0B52bDqlwf1F9djY4aG92X0JzOU0/view?usp=sharing)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -59,7 +81,13 @@ PageMod({
...
-exports.main = setDefaultPrefs;
+exports.main = function (opts) {
+  if (opts.reason === 'startup') { return; }
+  setDefaultPrefs();
+};
 
 // Covers uninstall, disable, shutdown, downgrade, upgrade.
-exports.onUnload = revertPrefs;
+exports.onUnload = function (reason) {
+  if (reason === 'shutdown') { return; }
```
Comment (cvan) [inline index.js:93]: I know this is correct

File: index.js [hunk 2]
```diff
@@ -59,7 +81,13 @@ PageMod({
 });
 
 // Covers startup, install, upgrade, downgrade, enable.
-exports.main = setDefaultPrefs;
+exports.main = function (opts) {
+  if (opts.reason === 'startup') { return; }
```
Comment (cvan) [inline index.js]: not sure if this is necessary

**Comment by cvan** [comment]
updated

**Comment by cvan** [comment]
r+

**Comment by cvan** [comment]
works fantastically :+1:
